spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/tp1
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.main.allow-bean-definition-overriding=true

application.security.jwt.secret=KO3OKE94303EKRO3I43KERKEI3K43OKO34K3KREKOR3KR3RK3R
application.security.jwt.issuer:spring-security
application.security.jwt.ttl-minutes:30